### ISSUE TITLE
Refactor plugin importing

### ISSUE THREAD

**Issue by tmessi** [yalp-log/yalp#2]
Input/parser/output import code is a bit awkward and requires specifying the full module and class in the config. Instead have the config allow specifying a list of packages for plugins:

``` yaml
input_packages:
  - 'yalp.inputs'
parser_packages:
  - 'yalp.parsers'
output_packages:
  - 'yalp.outputs'
```

Then inputs/parsers/outputs can be specified as follows:

``` yaml
inputs:
  - file:
      path: '/var/log/messages'

parsers:
  - regex:
      regex: '(?P<month>\w+)\s+(?P<day>\d+)'

outputs:
  - mongo:
      uri: 'mongodb://localhost:27017/yalp/'
      database: yalp
      collection: 'logs'
```

Where keys (ie `file`, `regex`, `mongo`) are python modules in the specified packages. Each plugin module should contain a single class named after the plugin type. Similar to how django does manage commands.
